// <auto-generated />
using LeagueManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LeagueManager.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180221040709_AddResultDescriptionAndStringLengths")]
    partial class AddResultDescriptionAndStringLengths
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LeagueManager.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("LeagueManager.Data.Entities.Team", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("Level");

                    b.Property<string>("Name")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("LeagueManager.Data.Entities.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Dates")
                        .HasMaxLength(100);

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("LeagueManager.Data.Entities.TournamentGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<bool?>("ParticipantAGameIsWinner");

                    b.Property<int?>("ParticipantATournamentGameId");

                    b.Property<int?>("ParticipantATournamentTeamId");

                    b.Property<bool?>("ParticipantBGameIsWinner");

                    b.Property<int?>("ParticipantBTournamentGameId");

                    b.Property<int?>("ParticipantBTournamentTeamId");

                    b.Property<string>("Result")
                        .HasMaxLength(50);

                    b.Property<string>("ResultLabel")
                        .HasMaxLength(50);

                    b.Property<string>("Tag")
                        .HasMaxLength(10);

                    b.Property<int>("TournamentId");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantATournamentGameId");

                    b.HasIndex("ParticipantATournamentTeamId");

                    b.HasIndex("ParticipantBTournamentGameId");

                    b.HasIndex("ParticipantBTournamentTeamId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentGames");
                });

            modelBuilder.Entity("LeagueManager.Data.Entities.TournamentGameTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Score");

                    b.Property<int>("TournamentGameId");

                    b.Property<int>("TournamentTeamId");

                    b.HasKey("Id");

                    b.HasIndex("TournamentGameId");

                    b.HasIndex("TournamentTeamId");

                    b.ToTable("TournamentGameTeams");
                });

            modelBuilder.Entity("LeagueManager.Data.Entities.TournamentTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Seed");

                    b.Property<int>("TeamId");

                    b.Property<string>("TeamNameOverride")
                        .HasMaxLength(30);

                    b.Property<int>("TournamentId");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentTeams");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("LeagueManager.Data.Entities.TournamentGame", b =>
                {
                    b.HasOne("LeagueManager.Data.Entities.TournamentGame", "ParticipantATournamentGame")
                        .WithMany("ParticipantATournamentGames")
                        .HasForeignKey("ParticipantATournamentGameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeagueManager.Data.Entities.TournamentTeam", "ParticipantATournamentTeam")
                        .WithMany("ParticipantATournamentGames")
                        .HasForeignKey("ParticipantATournamentTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeagueManager.Data.Entities.TournamentGame", "ParticipantBTournamentGame")
                        .WithMany("ParticipantBTournamentGames")
                        .HasForeignKey("ParticipantBTournamentGameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeagueManager.Data.Entities.TournamentTeam", "ParticipantBTournamentTeam")
                        .WithMany("ParticipantBTournamentGames")
                        .HasForeignKey("ParticipantBTournamentTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeagueManager.Data.Entities.Tournament", "Tournament")
                        .WithMany("TournamentGames")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LeagueManager.Data.Entities.TournamentGameTeam", b =>
                {
                    b.HasOne("LeagueManager.Data.Entities.TournamentGame", "TournamentGame")
                        .WithMany("TournamentGameTeams")
                        .HasForeignKey("TournamentGameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeagueManager.Data.Entities.TournamentTeam", "TournamentTeam")
                        .WithMany("TournamentGameTeams")
                        .HasForeignKey("TournamentTeamId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LeagueManager.Data.Entities.TournamentTeam", b =>
                {
                    b.HasOne("LeagueManager.Data.Entities.Team", "Team")
                        .WithMany("TournamentTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeagueManager.Data.Entities.Tournament", "Tournament")
                        .WithMany("TournamentTeams")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LeagueManager.Data.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LeagueManager.Data.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LeagueManager.Data.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LeagueManager.Data.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
